### ISSUE TITLE
Font-Awesome icons not in package

### ISSUE THREAD

**Issue by peterader** [akeeba/release-system#113] opened 2017-06-03 14:30 UTC
Hi, I noticed that the download ID page is now using font-awesome icons, which is pretty awesome! :) However, they are not included in the package. On Akeebabackup.com they are loaded by the template I believe however, if the used template does not include font-awesome it looks really buggy. Would be nice to handle that inside the extension.

![screenshot 2017-06-03 16 24 04](https://cloud.githubusercontent.com/assets/1409554/26754382/3b2c59de-487a-11e7-90ad-909edb59e55b.png)

**Comment by nikosdion** [comment] 2017-06-03 16:50
Feel free to add an option to load Font Awesome in the front-end and send us a Pull Request [per the README](https://github.com/akeeba/release-system/blob/development/README.md#no-support---for-developers-only) :)

**Comment by nikosdion** [comment] 2017-07-09 07:29
Upon further inspection I do not use Font Awesome icons. As you can see in `components/com_ars/View/DownloadIDLabels/tmpl/default.blade.php` I am using Bootstrap 2 icon classes, namely `icon-retweet` and `icon-trash`. The problem is that Joomla!'s default, core modified Bootstrap 2 distribution does not include the standard Bootstrap 2 icons. It has a _subset_ of them and they are replaced with IcoMoon icons.

Older versions of Akeeba Release System used Akeeba Strapper to load a complete, namespaced, Bootstrap 2 distribution in the front-end to let these icons appear. Since BS2 is dead and all commercial template clubs include a compatibility layer with BS2 I simply removed Strapper altogether from ARS.

This leaves you with two options:

1. Create template overrides to change the icons in the front-end
1. Use a template with a pristine Bootstrap 2 or Bootstrap 3 distribution instead of loading the bastardized monstrosity Joomla! ships by default.

Since this issue has nothing to do with using Font Awesome or any other third party icon set I am closing it.

**Closed by nikosdion** 2017-07-09 07:29 UTC
