### ISSUE TITLE
Class 'Akeeba\Engine\Postproc\Connector\S3v4\Configuration' not found when saving Category with s3:// Files Directory 

### ISSUE THREAD

**Issue by ryandemmer** [akeeba/release-system#116] opened 2017-07-06 08:50 UTC
When creating or updating a Category, setting the Files Directory value to an AWS S3 path using the s3:// prefix, results in an error:

Class 'Akeeba\Engine\Postproc\Connector\S3v4\Configuration' not found

Akeeba Release System v.3.2.3
Joomla 3.7.3

**Comment by nikosdion** [comment] 2017-07-09 07:17
This looks like a packaging issue. The contents of the `administrator/components/com_ars/vendor/akeeba/s3` folder are not present in the archive. I will investigate the root cause and publish a new release. In the meantime you can upload the contents of [the Akeeba Amazon S3 Connector repository](https://github.com/akeeba/s3) into that folder.

**Comment by nikosdion** [comment] 2017-07-09 07:21
Hm, trying to rebuild the package ZIP file I can see that the files are included just fine. I have no idea why the current release is broken.

I'll publish a new release later. I first need to publish a new FOF version which includes a workaround for a known Joomla! extensions updates bug (some files are not copied on update) since ARS could use it. I am closing this issue since it'll be de facto addressed on publishing a new release.

**Closed by nikosdion** 2017-07-09 07:21 UTC
