### ISSUE TITLE
Class 'Akeeba\Engine\Postproc\Connector\S3v4\Configuration' not found 

### ISSUE THREAD

**Issue by murphylas** [akeeba/release-system#127] opened 2017-12-26 22:59 UTC
I just installed the latest version of ARS 3.2.4

When I attempt to create a category, I get the following error message:

An error has occurred.

    0 Class 'Akeeba\Engine\Postproc\Connector\S3v4\Configuration' not found 

Return to Control Panel

I read your response to a report saying that the appropriate files were missing from the previous release 3.2.3. However apparently, the files are missing from the new release.

This is strange since a corrected ARS is being used to distribute Joomla.

**Comment by nikosdion** [comment] 2017-12-27 08:04
Thank you for the heads up! This was caused by an uninitialized Composer vendor folder. This is fixed in version 3.2.5.

**Closed by nikosdion** 2017-12-27 08:04 UTC
