### ISSUE TITLE
[3.0] Frontend Category Browse Requires Authentication

### ISSUE THREAD

**Issue by mbabker** [akeeba/release-system#85] opened 2015-11-08 01:55 UTC
The `\Akeeba\ReleaseSystem\Site\Controller\Category::execute()` method performs an ACL check that makes frontend browsing require an user be authenticated to the site.  This makes pages linked to from the "Entire repository" menu item type unusable for allowing public browsing.

Joomla 3.5.0-beta & ARS 3.0.0

**Comment by nikosdion** [comment] 2015-11-08 10:25
Um, no. Because the actual code reads
if (!in_array($format, ['html', 'feed']) && !($this->checkACL('core.manage') || $this->checkACL('core.admin')))
In other words the ACL check is only performed when the format is anything other than a regular HTML page or RSS/Atom feed. Since the links from the Entire Repository page have implicitly format=html this ACL check is never triggered. Moreover you'll see that we do 

// For the HTML view we only allow browse
if (in_array($format, ['html', 'feed']))
{
   $task = 'browse';
}
I think that explains why we have the ACL checks: they only apply when you're using the RESTful API ;)

I cannot reproduce this issue. Maybe you're doing something funky in your overrides?

**Comment by nikosdion** [comment] 2015-11-09 08:15
Closing as side effect of gh-86

**Closed by nikosdion** 2015-11-09 08:15 UTC
