### ISSUE TITLE
Releases with the same alias are messed

### ISSUE THREAD

**Issue by sakiss** [akeeba/release-system#190] opened 2021-11-10 18:51 UTC
Hi Nichola

I am having the following issue:
When i release 2 versions with the same name, under different bleeding edge categories, their download files are messed in the front-end.

For example i have 2 categories:
a. FREE
b. PRO

When i release the same version in both (e.g. 1.0.0) and then visit my downloads area, the FREE > 1.0.0 could give me the file of PRO > 1.0.0 and vice versa. 
This happens every time i release without exception and seems to happen in 2 different installations i tested that.
 
Version 7.0.2 in Joomla 4

**Comment by nikosdion** [comment] 2021-11-10 20:02
There are many red flags here.

BleedingEdge releases are meant for development releases, not regular versions. So, let's start with the fact that you're using the wrong tool for the job.

Second, each category only parses files in its own folder. Each category must have a unique folder. It sounds like you are using the same folder in two different categories. This will not work.

**Comment by sakiss** [comment] 2021-11-11 11:51
Thanks for the feedback.

> BleedingEdge releases are meant for development releases, not regular versions. So, let's start with the fact that you're using the wrong tool for the job.

I am aware, but fits me quite well as it lets me make a release in a fast way.
If there is another way to fast track that process, i am open.

> Second, each category only parses files in its own folder. Each category must have a unique folder. It sounds like you are using the same folder in two different categories. This will not work.

Each of the releases i mentioned are under different category, hence different folder.
e.g.
folder/free/1.0.0
folder/pro/1.0.0

Also their url paths are different:
e.g. 
example.com/download/free/1.0.0
example.com/download/pro/1.0.0

Despite that. when i visit the free it can give me the pro file and vice versa.

If you need more details, please let me know.

**Comment by nikosdion** [comment] 2021-11-11 12:11
> If there is another way to fast track that process, i am open.

We use [Akeeba Release Maker](https://github.com/akeeba/releasemaker) for our software. It works great with [Build Tools](https://github.com/akeeba/buildfiles/). Releasing something for me is typically something as easy as `git tag 1.2.3 -sm "Tagging 1.2.3" && git push --tags && cd build && phing all release -Dversion=1.2.3`

> Despite that. when i visit the free it can give me the pro file and vice versa.

I am not sure why you get that. I am using the same thing to publish development releases which do have the same folder name under a different parent folder for the core and pro versions. For example, I have something like `releases/dev/backup-pro/rev1234abc` and `releases/dev/backup-core/rev1234abc`.

It sounds like the SEF router is picking up the wrong menu item. Try creating a hidden menu structure like this:
```
Downloads (entire repository view)
  +-- Whatever Free (category view)
  +-- Whatever Paid (category view)
```
This will disambiguate the Itemid when creating the SEF URL.

**Comment by sakiss** [comment] 2021-11-11 12:18
> We use Akeeba Release Maker for our software. It works great with Build Tools.

Thanks for pointing out!
I am using my own phing based tool, for building the extension. But have not found any way to automate the release in ARS.
I suppose Akeeba Release Maker does that?

> It sounds like the SEF router is picking up the wrong menu item. Try creating a hidden menu structure like this:

I tried that too. 
Seems like the Router resolves the url, using only the last part of the path.

Did you checked that on Joomla 4?
If you need access or a backup of the site, can be provided.

**Comment by nikosdion** [comment] 2021-11-11 12:35
> I suppose Akeeba Release Maker does that?

Yes.

> Seems like the Router resolves the url, using only the last part of the path.

Are we talking about building a URL or parsing a URL? I was talking about building a URL.

Parsing a URL takes all segments into account. I have checked that. That fucking router took forever to write since Joomla seems to have zero usable documentation about the new router. I was following what it's doing with Xdebug and phpStorm. Still, the only way to always parse a SEF URL in a way that returns the correct Itemid requires having one menu item per category.  The SEF URL then becomes `menu_item_alias/release_version/item_alias`. Joomla parses up to and including the menu_item_alias and gives us an Itemid corresponding to this category and a `$segments` array which has the release_version and item_alias. The router rules populate the release ID from the first segment (`release_version`) and then the download item ID is populated by the second segment. That's how routing works on Joomla 4 specifically. The parsing takes place in core Joomla code, we only provide the short methods in the router which convert the segments to the corresponding ID. Which methods will be used when is decided by Joomla itself.

If you do not have a menu item per category things get complicated because you now have three segments in the SEF URL: category alias, release version and item alias. If the category alias matches the wrong category and since you have the exact same release version and item alias in both categories you might indeed end up with the wrong item ID.

**Comment by nikosdion** [comment] 2021-11-11 12:36
It also does not make sense for you to have public releases with separate categories for free and paid. Use one category with the product name and upload two files per release, the free and paid versions, with different access levels. That's how we do it.

**Comment by laoneo** [comment] 2021-11-11 12:37
We too do it that way.

Had a similar experience with the router.

**Comment by nikosdion** [comment] 2021-11-11 12:38
Since I cannot reproduce this on my sites and you guys are developers, how about you give it a shot at debugging?

**Comment by laoneo** [comment] 2021-11-11 12:40
I'm still using version 5 and all works more or less as expected. Upgrade is postponed till the site will be lifted to version 4.

**Comment by sakiss** [comment] 2021-11-11 12:42
I will give it a try to do some debugging once i have a bit of time.

**Comment by nikosdion** [comment] 2022-03-23 07:46
Closing as no further feedback has been provided in 4 months.

**Closed as completed by nikosdion** 2022-03-23 07:46 UTC
