### ISSUE TITLE
Link Created by ARS Item Button Kicks Out Errors

### ISSUE THREAD

**Issue by murphylas** [akeeba/release-system#129] opened 2018-01-10 07:15 UTC
I am using the ARS Item Button in an Article to reference a download. The plugin produces the following URL:

https://test.themannareserve.org/index.php?option=com_ars&view=Item&id=2

When a user clicks on the above link, the following error is shown:

403
Access forbidden.

The page you are looking for was moved, removed, renamed or might never existed.
Go to the Home Page

The access for both the category and the item are set to public.

If I copy the URL used by the ARS Repository for the same download into an article, the link appears as:

https://test.themannareserve.org/index.php/ars-repository/marilyn-hickey-category/downloads-release/angels-all-around-hickey?format=zip

This link works perfectly. I can download.

Please explain why one works and the other does not. How do I fix this?

Thank you in advance.

**Comment by nikosdion** [comment] 2018-01-18 15:06
I have not had the time to look into this yet due to the birth of our daughter. Once I have some more time I will take a look and let you know what is going on.

**Comment by murphylas** [comment] 2018-01-19 01:18
Congrats!

**Comment by murphylas** [comment] 2018-01-31 12:28
I wrote a snippet which solves the problem. It also creates a nice download button with the file size and download count.  It checks if the end user has signed in and it tells them to sign in if they haven't. Also, the ars-repository is the alias of the menu item ars browser. I had to hard code this to get it to work.

HTH.

[ShowDownloadLink2.zip](https://github.com/akeeba/release-system/files/1681637/ShowDownloadLink2.zip)

**Comment by nikosdion** [comment] 2018-02-01 18:21
Finally I had time to look into this. In short: there is no bug; check your menu structure.

The link generated by the plugin is absolutely correct. Just like Joomla's link to article button, the ARS button plugin generates a non-SEF URL without an Itemid by design. When Joomla displays the article it will process all of the relative, non-SEF URLs during the onContentPrepare stage and replace them with SEF URLs. The replacement of non-SEF with SEF URLs is implemented in Joomla by passing the non-SEF URLs through `JRoute:_()`. In its turn, it ends up using the functions inside each component's `router.php` file. 

Routing URLs in Joomla is complicated because it has a multilevel routing architecture. What I mean is that the menu items define not only the URL path for the component and view they target but also other URLs of the same component. As documented, you **MUST** create a menu item to the repository's root. If you have created other menu items to categories, releases, items etc they **MUST** have an Itemid higher than the link pointing to the repository root.

Moreover, you **MUST NOT** create more specific menu items with an access level lower than all of its sub-items in ARS. Let's say you have Category "Foo" with access public, release "1.0" with access public and an item "bar.zip" with access public. If you create a menu item pointing to release 1.0 with access Registered then _ALL_ links to the "bar.zip" item will require the user to be logged in. That's because the SEF router will pick up the most specific menu item (the one to the release). Joomla sees that in the URL and goes "hey, you, you are NOT logged in, sod off" and throws a 403.

Of course this is all documented and has nothing to do with ARS but with the way Joomla's SEF router works. So I'm going to close this as invalid since the plugin generates exactly the URL it should be creating.

As for your code snippet, it works on _your_ site and _your_ site's menu structure - by accident! If you try to use this code on another site... well, if the menu structure isn't _just so_ you will get loads of 404s.

**Closed by nikosdion** 2018-02-01 18:21 UTC

**Comment by murphylas** [comment] 2018-02-05 01:26
Actually, the URL generated by the ARS plugin is not the correct URL. This causes the error. If you shut off SEF friendly URLs, this becomes obvious. The URL generated by the ARS plugin is:

index.php?option=com_ars&view=Item&id=4

The URL that works is:

index.php?option=com_ars&view=Item&task=download&format=raw&id=4&Itemid=0

HTH.
